[package]
name = "arc-network"
version = "0.1.0"
authors = ["jam1garner <jam1.mcleod@hotmail.com>"]
edition = "2018"

[package.metadata.skyline]
titleid = "01006A800016E000"

[lib]
crate-type = ["cdylib"]

[dependencies]
skyline = { git = "https://github.com/ultimate-research/skyline-rs.git" }
network-reader-adapter = { git = "https://github.com/jam1garner/network-reader.git" }
[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
lto = true
